import React from 'react';
import styles from './FAQ.module.css';

import picture from "../../../Asset/FAQ_Sample.webp";

const FAQ = () => {
    return (
        <section className={styles.cirtIntro}>
            {/* this is written by ChatGPT */}
            <div className = {styles.wordsContainer}>
                <h1> Research, Publish, Inspire — All in One Place</h1>
                <span>Welcome to CIRT - the central hub for Criminal Justice research, publishing, and innovation</span>
                <input type='checkbox' id = 'expanded'/>
                <label for="expanded" role="button"></label>
                <p className = {styles.longerDes} >Established in 2023, CIRT bridges the gap between UT Scholars, graduate students, and Criminal Justice agencies by providing a platform to showcase research, share resources, and support academic publishing. Explore our digital repository of research posters, submit and review academic papers through our online journal, and access tools to advance your career in this ever-evolving field. Join us as we drive progress through research, scholarship, and real-world impact.</p>
            </div>

            <div className = {styles.imgContainer}>

                {/* this img is generated by ChatGPT */}
                <img src = {picture} alt = "There is supposed to be an img here"/>
            </div>
        </section>
    );
};
export default FAQ;